services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: branbdev
      POSTGRES_PASSWORD: thefarmersbride
      POSTGRES_DB: acrospec_db
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U branbdev -d acrospec_db']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  node_modules:
